### ISSUE TITLE
How about separating versions by branch?

### ISSUE THREAD

**Issue by nanikit** [beat-forge/beatsaber-stripped#5]
### Background
I'm considering using this repository as a submodule, but I'm hesitant due to the file size after cloning.

I've contemplated using `init-beatsaber`, but I believe the submodule approach is preferable in terms of both simplicity and security, as it avoids the need for a GitHub token.

### Suggestion
Create branches (e.g., v1.29.1) containing all files only for that version while preserving the directory structure.

### Considered Alternative
None.

**Comment by ChecksumDev** [comment]
I never considered sub-modules, completely forgot those existed to be honest. I can give something like this a shot when I have time. ^^

**Comment by nanikit** [comment]
After some experiments, I realized that simply forking and removing some files is easier way.
